name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} on Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-13
          - macos-latest
        ruby:
          - '3.3.3'
          - '3.2.4'
          - '3.1.6'
          - '3.0.7'
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Update package database
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update -qq

    - name: Install required packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y gcc-multilib
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev

    - name: Run the default task
      run: bundle exec rake

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rubyraylib-${{ matrix.os }}-${{ matrix.ruby }}
        path: ${{ github.workspace }}/lib/rubyraylib
        retention-days: 90
