name: macOS

on:
  push:
  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        os:
          - macos-13
          - macos-latest
        ruby:
          - '3.3.3'
          - '3.2.4'
          - '3.1.6'
          - '3.0.7'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Build Raylib
      working-directory: ${{ github.workspace }}/third_party/raylib/src
      run: |
        export CFLAGS="-flto -Ofast -DNDEBUG -fpic -ftree-vectorize"
        make

    - name: Run the default task
      run: bundle exec rake compile

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rubyraylib-${{ matrix.os }}-${{ matrix.ruby }}
        path: ${{ github.workspace }}/lib/rubyraylib
        retention-days: 90
