name: Windows Binary

on:
  workflow_dispatch:
  push:
    paths:
      - 'ext/rubyraylib/**'
      - 'CMakeLists.txt'
      - 'third_party/**'
      - '.github/workflows/windows.yml'
  pull_request:
    paths:
      - 'ext/rubyraylib/**'
      - 'CMakeLists.txt'
      - 'third_party/**'
      - '.github/workflows/windows.yml'

jobs:
  build-windows:
    name: windows-x86_64
    runs-on: windows-latest
    env:
      OS: windows
      ARCH: x86_64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: >-
            base-devel
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-ninja

      - name: Configure CMake
        shell: msys2 {0}
        run: cmake -B build -DCMAKE_BUILD_TYPE:STRING=Release

      - name: Build CMake
        shell: msys2 {0}
        run: cmake --build build --config Release --target all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: raylib-cruby-${{ env.ARCH }}
          path: |
            ${{ github.workspace }}/build/*.exe
            ${{ github.workspace }}/build/*.dll
          retention-days: 90

